### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [optimisemediagroup/optimise-gtm-universal-conversion-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We see console errors while trying to run the code. Please resolve the issue.
![Screenshot 2021-09-10 1 39 37 PM](https://user-images.githubusercontent.com/53495700/132915110-c05f9d06-eafe-42c1-b45c-09bd948c06d2.png)

**Comment by huntg** [comment]
Thanks for your feedback. A fix has been uploaded. Please can you check and confirm.

**Comment by huntg** [comment]
Hi @praveena-pappu just checking whether this is ready to be re-reviewed?

Thanks

**Comment by praveena-pappu** [comment]
We still see the error in the console. Can you please check and resolve.
![Screenshot 2021-09-16 2 24 37 PM](https://user-images.githubusercontent.com/53495700/133687767-09387566-39b0-4f59-a50b-381f478300c6.png)

**Comment by huntg** [comment]
Resolved additional issues and closed with fixes. @praveena-pappu please review again. Thanks

**Comment by huntg** [comment]
@praveena-pappu can you please review this again now its been resolved. Thanks

**Comment by huntg** [comment]
@praveena-pappu can you please review this again now its been resolved and some tests added. 

Thanks
